### ISSUE TITLE
1/1/24 2.2.0 Alpha 2 Playtest

### ISSUE THREAD

**Issue by CasuallyJack** [KosmosMC/Neodymium#6]
# Device specs

OS: EndeavourOS Linux x86_64

CPU: AMD Ryzen 7 3800XT (16) @ 3.900GHz

GPU: AMD ATI Radeon RX 7700 XT / 7800 XT

Memory: 32 GB

# Potential Issues
- [ ] Lighthouse structures spawn in oceans.
![2024-01-01_21 36 30](https://github.com/Vladivaston/Neodymium/assets/75509840/625ed0f8-12bc-46fe-ad52-c29c47d48bb3)

- [x] Certain mobs (such as zombies and skeletons) sometimes gain damage while rising from the ground during the night.
- [x] ~~Water can be placed in tree leaves using a water bucket.~~ Is an actual feature
![2024-01-01_21 54 53](https://github.com/Vladivaston/Neodymium/assets/75509840/5b54a28f-091a-466d-95d3-1ffbd0187743)

**Comment by Vladivaston** [comment]
1 will hopefully be fixed in alpha.
2 unfixable (to my knowledge. Will still try, though)
3 is a feature added by mojang

**Comment by Vladivaston** [comment]
mostly fixed (hopefully!!)
